-- System: Mission Task & Execution Management Database

-- Purpose: Manage and monitor operational tasks performed by
-- astronauts during missions. Supports structured task planning,
-- assignment of responsibilities, and systematic tracking
-- of execution progress.

-- 1. USUWANIE TABEL

DROP TABLE Experiment_Crew   CASCADE CONSTRAINTS;
DROP TABLE Task              CASCADE CONSTRAINTS;
DROP TABLE Experiment        CASCADE CONSTRAINTS;
DROP TABLE Crew              CASCADE CONSTRAINTS;
DROP TABLE Agency            CASCADE CONSTRAINTS;
DROP TABLE Category          CASCADE CONSTRAINTS;
DROP TABLE Priority          CASCADE CONSTRAINTS;
DROP TABLE Task_Status       CASCADE CONSTRAINTS;


-- 2. TABELE

-- Poziomy priorytetow zadan
CREATE TABLE Priority (
    priority_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name          VARCHAR2(10)  NOT NULL UNIQUE,       -- Low, Medium, High, Critical
    sort_order    NUMBER(2)     NOT NULL UNIQUE         -- 1=najniższy, 4=najwyższy
);

-- Statusy wykonania zadan
CREATE TABLE Task_Status (
    status_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name          VARCHAR2(20)   NOT NULL UNIQUE,       -- Planned, In Progress, On Hold, Completed, Cancelled
    description   VARCHAR2(200),
    sort_order    NUMBER(2)      NOT NULL UNIQUE
);

-- Kategorie eksperymentow naukowych
CREATE TABLE Category (
    category_id   NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name          VARCHAR2(50)   NOT NULL UNIQUE,
    description   VARCHAR2(200)  NOT NULL
);

-- Agencje kosmiczne
CREATE TABLE Agency (
    agency_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name          VARCHAR2(20)   NOT NULL UNIQUE,       -- Skrót agencji (NASA, ESA itp.)
    full_name     VARCHAR2(100),                        -- Pełna nazwa
    country       VARCHAR2(50)   NOT NULL
);


-- ============
-- Czlonkowie załogi
CREATE TABLE Crew (
    crew_id       NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    first_name    VARCHAR2(50)   NOT NULL,
    last_name     VARCHAR2(50)   NOT NULL,
    role          VARCHAR2(50)   NOT NULL,
    date_of_birth DATE,
    country       VARCHAR2(50)   NOT NULL
);

-- Eksperymenty naukowe
CREATE TABLE Experiment (
    experiment_id     NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name              VARCHAR2(100)  NOT NULL,
    description       VARCHAR2(500),
    agency_id         NUMBER(10)         NOT NULL  CONSTRAINT experiment_agency_fk    REFERENCES Agency(agency_id),
    category_id       NUMBER(10)         NOT NULL  CONSTRAINT experiment_category_fk  REFERENCES Category(category_id),
    facility_manager  NUMBER(10)                   CONSTRAINT experiment_manager_fk   REFERENCES Crew(crew_id),
    start_date        DATE,
    end_date          DATE,
    CONSTRAINT experiment_dates_chk CHECK (end_date IS NULL OR end_date >= start_date)
);

-- Zadania w ramach eksperymentow
CREATE TABLE Task (
    task_id          NUMBER(10) GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
    name             VARCHAR2(100)      NOT NULL,
    description      VARCHAR2(2000),
    experiment_id    NUMBER(10)         NOT NULL              CONSTRAINT task_experiment_fk  REFERENCES Experiment(experiment_id),
    assigned_to      NUMBER(10)                               CONSTRAINT task_crew_fk        REFERENCES Crew(crew_id),
    priority_id      NUMBER(10)         DEFAULT 1  NOT NULL   CONSTRAINT task_priority_fk    REFERENCES Priority(priority_id),
    status_id        NUMBER(10)         DEFAULT 1  NOT NULL   CONSTRAINT task_status_fk REFERENCES Task_Status(status_id),
    planned_date     DATE,
    completed_date   DATE,
    duration_minutes NUMBER(6)
);


-- 3. TABELA Wiele do wielu

-- Przypisanie członków załogi do eksperymentów
CREATE TABLE Experiment_Crew (
    experiment_id   NUMBER(10)  NOT NULL  CONSTRAINT expcrew_experiment_fk  REFERENCES Experiment(experiment_id),
    crew_id         NUMBER(10)  NOT NULL  CONSTRAINT expcrew_crew_fk        REFERENCES Crew(crew_id),
    assigned_date   DATE        DEFAULT SYSDATE,
    CONSTRAINT experiment_crew_pk PRIMARY KEY (experiment_id, crew_id)
);

-- 4. INDEKSY

CREATE INDEX idx_task_experiment    ON Task(experiment_id);
CREATE INDEX idx_task_assigned      ON Task(assigned_to);
CREATE INDEX idx_task_status        ON Task(status_id);
CREATE INDEX idx_task_priority      ON Task(priority_id);
CREATE INDEX idx_experiment_agency  ON Experiment(agency_id);

COMMIT;
